---
- name: set up log rotation for glance
  logrotate: name=glance path=/var/log/glance/*.log
  args:
    options:
      - daily
      - missingok
      - rotate 7
      - compress
      - notifempty
      - delaycompress
  when: openstack_install_method != 'distro'

