---
dependencies:
  - role: openstack-meta
  - role: endpoints
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
  - role: logging-config
    when: logging.enabled|default(True)|bool
    service: magnum
    logdata: "{{ magnum.logs }}"
  - role: openstack-source
    project_name: magnum
    project_rev: "{{ magnum.source.rev }}"
    virtualenv: "{{ magnum.source.virtualenv }}"
    system_dependencies: "{{ magnum.source.system_dependencies }}"
    python_dependencies: "{{ magnum.source.python_dependencies }}"
    upper_constraints: "{{ magnum.source.upper_constraints }}"
    alternatives: "{{ magnum.alternatives }}"
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: magnum
    alternatives: "{{ magnum.alternatives }}"
    when: openstack_install_method == 'package'
  - role: collectd-plugin
    when: collectd is defined and collectd.enabled|bool
  - role: openstack-database
    database_name: magnum
  - role: openstack-distro
    project_name: magnum
    project_packages: "{{ magnum.distro.project_packages }}"
    when: openstack_install_method == 'distro'
  - role: openstack-firewall
    rule_name: magnum
    rules_type_input:
      - { protocol: tcp, port: "{{ endpoints.magnum.port.haproxy_api }}" }
