---
- name: neutron process check
  sensu_process_check: service=neutron-server
  notify: restart sensu-client

- name: neutron free fips check
  sensu_check: name=check-neutron-free-fips plugin=check-neutron-fip.sh state=absent
  notify: restart sensu-client

- name: neutron free fips metrics check
  sensu_metrics_check: name=neutron-free-fips-metric plugin=check-neutron-fip.sh state=absent
  notify: restart sensu-client

- name: neutron metrics
  template: src=etc/collectd/plugins/neutron.conf dest=/etc/collectd/plugins/neutron.conf
  notify: restart collectd
  when: collectd is defined and collectd.enabled|bool
  tags: collectd

- name: neutron sla metrics
  sensu_metrics_check: name=neutron-sla-metrics plugin=metrics-os-api.py
                       args='-S neutron --scheme {{ monitoring.graphite.cluster_prefix }}'
                       only_on_ip="{{ undercloud_floating_ip | default(floating_ip) }}"
  notify: restart sensu-client

- name: lbaas sla metrics
  sensu_metrics_check: name=lbaas-sla-metrics plugin=metrics-os-api.py
                       args='-S lbaas --scheme {{ monitoring.graphite.cluster_prefix }}'
                       only_on_ip="{{ undercloud_floating_ip | default(floating_ip) }}"
  when: (neutron.lbaas.enabled == "smart" and
        groups['controller'][0] not in groups['compute']) or
        neutron.lbaas.enabled|bool
  notify: restart sensu-client
  
- name: neutron agents check
  sensu_check_dict:
    name: "check-neutron-agents"
    check: "{{ sensu_checks.neutron.check_neutron_agents }}"
    only_on_ip: "{{ undercloud_floating_ip | default(floating_ip) }}"
  notify: restart sensu-client missing ok

- name: neutron agents duplicate check
  sensu_check_dict:
    name: "check-neutron-agents-duplicate"
    check: "{{ sensu_checks.neutron.check_neutron_agents_duplicate }}"
    only_on_ip: "{{ undercloud_floating_ip | default(floating_ip) }}"
  notify: restart sensu-client missing ok

- name: template neutron l3 router script for ucarp
  template: src=check-neutron-l3-routers.sh mode=0755 owner=root group=root
            dest=/etc/sensu/plugins/check-neutron-l3-routers.sh

- name: neutron router check multiple l3 agents active or all standby status
  sensu_check_dict:
    name: "check-neutron-l3-routers"
    check: "{{ sensu_checks.neutron.check_neutron_l3_routers }}"
  notify: restart sensu-client missing ok

