---
dependencies:
  - role: endpoints
  - role: apt-repos
    repos:
      - name: 'haproxy package repo'
        repo: 'deb {{ apt_repos.haproxy.repo }} {{ ansible_lsb.codename }} main'
        key_url: '{{ apt_repos.haproxy.key_url }}'
    when: ansible_distribution in ['Ubuntu']
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
  - role: collectd-plugin
    when: collectd is defined and collectd.enabled|bool
