---
- name: ceilometer-polling process check
  sensu_process_check: service=ceilometer-polling
  notify: restart sensu-client

- name: remove retired process checks
  sensu_process_check:
    service: ceilometer-agent-compute
    state: absent
  notify: restart sensu-client
