---
- name: add nova to the docker group
  user: name=nova groups=docker append=true system=yes createhome=no

- name: get novadocker source repo
  git: |
    repo={{ nova.driver.docker.git_mirror }}
    dest={{ nova.driver.docker.dest }}
    version={{ nova.driver.docker.rev }}
    update={{ openstack.git_update }}
  register: git_novadocker
  until: git_novadocker|success
  retries: 3
  delay: 60

- name: pip install novadocker
  pip: name='{{ nova.driver.docker.dest }}'
       extra_args='-i {{ openstack.pypi_mirror }}'
  register: result
  until: result|success
  retries: 3
  delay: 60
  when: git_novadocker|changed and openstack_install_method == 'source'
  notify:
    - novadocker rootwrap
    - restart nova compute

- name: pip install novadocker
  pip: name='{{ nova.driver.docker.dest }}'
       extra_args='-i {{ openstack.pypi_mirror }}'
       virtualenv='/opt/bbc/openstack-{{ openstack_package_version }}/nova/'
  register: result
  until: result|success
  retries: 3
  delay: 60
  when: git_novadocker|changed and openstack_install_method == 'package'
  notify:
    - novadocker rootwrap
    - restart nova compute
