---
- name: set up log rotation for cinder
  logrotate: name=cinder path=/var/log/cinder/*.log
  args:
    options:
      - daily
      - missingok
      - rotate 7
      - compress
      - notifempty
      - delaycompress
  when: openstack_install_method != 'distro'
 
