---
dependencies:
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
  - role: logging-config
    when: logging.enabled|default(True)|bool
    service: ceph
    logdata: "{{ ceph.logs }}"
  - role: ceph-config
  - role: repos
    repos:
      - repo: 'deb {{ apt_repos.ceph.repo }} {{ ansible_lsb.codename }} main'
        key_url: '{{ apt_repos.ceph.key_url }}'
    when: ursula_os == 'ubuntu'
# as redhat already has ceph repo added, we don't need to add it here
