---
- name: set up log rotation for ironic
  logrotate: name=ironic path=/var/log/ironic/*.log
  args:
    options:
      - daily
      - missingok
      - rotate 7
      - compress
      - notifempty
      - delaycompress
  when: openstack_install_method != 'distro'
 
