---
- name: set up log rotation for heat
  logrotate: name=heat path=/var/log/heat/*.log
  args:
    options:
      - daily
      - missingok
      - rotate 7
      - compress
      - notifempty
      - delaycompress
  when: openstack_install_method != 'distro'

