---
- name: logstash-forwarder config directory
  file: dest=/etc/logstash-forwarder.d state=directory mode=0755

- name: install log template
  template: src=etc/logstash-forwarder.d/template.conf dest=/etc/logstash-forwarder.d/{{ service }}.conf
  notify: restart logstash-forwarder

