name: Ursula
title: Compliance Audit
maintainer: Ursula Team
copyright: IBM
copyright_email:
license: Apache 2.0
summary: An InSpec Compliance Profile
version: 0.1.0
depends:
- name: {{ inspec.profiles[inspec.controls[item].profile].name }}
  path: '/etc/inspec/profiles/{{ inspec.profiles[inspec.controls[item].profile].name }}-current'
