---
- name: restart swift-proxy service
  service: name="{{ swift.services.swift_proxy.name }}" state=restarted
  when: start_proxy|bool

- name: restart haproxy
  service: name=haproxy state=restarted

