---
- name: database users
  run_once: true
  mysql_user: name={{ database_name }} host=%
              password={{ secrets.db_password }}
              priv={{ database_name }}.*:ALL
              state=present

- name: remove local database users (since absence of anonymous user will allow access as wildcard)
  run_once: true
  mysql_user: name={{ database_name }} host=localhost state=absent

- name: "create database {{ database_name }}"
  run_once: true
  mysql_db: db={{ database_name }} state=present
  register: database_create
