---
- name: create collectd user
  user: name=collectd comment=collectd shell=/bin/false
        system=yes home=/nonexistent createhome=no
        append=true groups=monitor

- name: install collectd packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - collectd
    - collectd-utils
    - collectd-core
  register: result
  until: result|succeeded
  retries: 5

- name: create config dirs
  file: dest={{ collectd.plugin_conf_dir }} state=directory owner=root mode=0755

- name: configure collectd
  template: src=etc/collectd/collectd.conf dest=/etc/collectd/collectd.conf
  notify:
    - restart collectd

- name: configure base collectd plugins
  template: src=etc/collectd/plugins/{{ item.key }}.conf dest={{ collectd.plugin_conf_dir }}/{{ item.key }}.conf
  with_dict: "{{ collectd.plugins }}"
  when: item.value.enabled|bool
  notify:
    - restart collectd

- name: set up log rotation for collectd
  logrotate: name=collectd path={{ collectd.plugins.logfile.file }}
  args:
    options:
      - daily
      - missingok
      - rotate 7
      - compress
      - postrotate
      - /bin/kill -HUP `cat /var/run/collectdmon.pid 2> /dev/null` 2> /dev/null || true
      - endscript

- meta: flush_handlers

- name: ensure apache is running
  service: name=collectd state=started
