---
- name: restart aodh services
  service: name={{ item.name }} state=restarted must_exist=false
  when: restart|default(True)
  with_items:
    - "{{ aodh.services.aodh_api }}"
    - "{{ aodh.services.aodh_evaluator }}"
    - "{{ aodh.services.aodh_listener }}"
    - "{{ aodh.services.aodh_notifier }}"
