---
# these two tasks are used to removed duplicated
# logrotate config file which created in previous
# version(on ubuntu). We won't need these 2 tasks
# when we have run these tasks on all envs at lest once
- name: check if ceph.conf exists
  stat: path=/etc/logrotate.d/ceph.logrotate
  register: result

- name: remove /etc/logrotate.d/ceph
  file: path=/etc/logrotate.d/ceph state=absent
  when: result.stat.exists
