---
- block:
  - name: remove invalid configuration for pam_unix
    lineinfile: dest=/etc/pam.d/common-password regexp=(pam_unix.so) state=absent
                line="password [success=7 default=ignore] pam_unix.so obscure sha512"
  
  - name: remove invalid configuration for pam_cracklib
    lineinfile: dest=/etc/pam.d/common-password regexp=(pam_cracklib.so) state=absent
                line="password requisite pam_cracklib.so ucredit=0 lcredit=-1 dcredit=-1 ocredit=0 minlen=8 retry=3"
  
  - name: implement password controls for pam.d login
    lineinfile:
      dest: "{{ item[0] }}"
      state: absent
      line: "{{ item[1] }}"
    with_nested:
      - [ /etc/pam.d/login, /etc/pam.d/passwd, /etc/pam.d/sshd, /etc/pam.d/su ]
      - [ "auth include common-auth", "account include common-account", "password include common-password" ]
    
  - name: prevent resuse of passwords
    lineinfile: dest=/etc/pam.d/common-password regexp=(pam_unix.so) state=present
                line="password [success=1 default=ignore] pam_unix.so obscure use_authtok sha512 remember=7 shadow"
                insertafter='^# here are the per-package modules'
                create=true
  
  - name: implement password complexity
    lineinfile: dest=/etc/pam.d/common-password regexp=(pam_cracklib.so) state=present
                line="password requisite pam_cracklib.so ucredit=0 lcredit=-1 dcredit=-1 ocredit=0 retry=3 minlen=8 difok=3 reject_username"
                insertafter='^# here are the per-package modules'
                create=true
    
  when: ursula_os == 'ubuntu'

- block:
  - name: set password history to last seven
    lineinfile:
      dest: /etc/pam.d/system-auth
      line: "password    required      pam_pwhistory.so remember=7 use_authtok"
      state: present
      insertafter: '^password\s+\w+\s+pam_pwquality.so'
  
  - name: set the password policy for centos/rhel
    template: src=etc/security/pwquality.conf dest=/etc/security/pwquality.conf
  
  when: ursula_os == 'rhel'

- name: set maximum password age
  lineinfile: dest=/etc/login.defs regexp=^PASS_MAX_DAYS
              line="PASS_MAX_DAYS   90" state=present

- name: set minimum password age
  lineinfile: dest=/etc/login.defs regexp=^PASS_MIN_DAYS
              line="PASS_MIN_DAYS   1" state=present

