---
- name: remove older libruby
  package:
    name: libruby1.8
    state: absent
  register: result
  until: result|succeeded
  retries: 5

- name: install system tools
  package:
    name: "{{ item }}"
  with_items: "{{ common.system_tools[ursula_os].packages }}"
  register: result
  until: result|succeeded
  retries: 5

- name: install tools for x86
  package: name={{ item }}
  with_items:
    - ack-grep
  when: ansible_architecture != "ppc64le" and ursula_os == "ubuntu"
  register: result
  until: result|succeeded
  retries: 5

- name: install selinux tooling
  package:
    name: policycoreutils-python
  when: ursula_os == 'rhel'
  register: result
  until: result|succeeded
  retries: 5

- name: load vlan module
  lineinfile: dest=/etc/modules
              line="8021q"
  when: ursula_os == 'ubuntu' and ansible_distribution_version == "14.04"

- name: install mcelog package
  package: name=mcelog
  when: common.system_tools.mcelog|bool and
        ansible_architecture != "ppc64le"
  register: result
  until: result|succeeded
  retries: 5

# http://www.supermicro.com/support/faqs/faq.cfm?faq=14537
- name: blacklist mei
  lineinfile:
    dest: /etc/modprobe.d/blacklist.conf
    line: "blacklist {{ item }}"
    create: yes
  with_items:
    - mei
    - mei_me

- name: install lm-sensors package
  package:
    name: "{{ common.system_tools[ursula_os].lm_sensors_package }}"
    state: present
    update_cache: yes
  notify:
    - load sensors
  register: result
  until: result|succeeded
  retries: 5

- meta: flush_handlers
