---
- name: set up log rotation for aodh
  logrotate: name=aodh path=/var/log/aodh/*.log
  args:
    options:
      - daily
      - missingok
      - rotate 7
      - compress
      - notifempty
      - delaycompress
  when: openstack_install_method != 'distro'

