---
- name: aodh-api process check
  sensu_process_check: service=aodh-api
  notify: restart sensu-client

- name: aodh-evaluator process check
  sensu_process_check: service=aodh-evaluator
  notify: restart sensu-client

- name: aodh-expirer process check
  sensu_process_check: service=aodh-expirer state=absent
  notify: restart sensu-client

- name: aodh-listener process check
  sensu_process_check: service=aodh-listener
  notify: restart sensu-client

- name: aodh-notifier process check
  sensu_process_check: service=aodh-notifier
  notify: restart sensu-client

- name: aodh-api check
  sensu_check: name=check-aodh-api plugin=check-os-api.rb
               args="--service aodh --criticality {{ aodh.monitoring.sensu_checks.check_aodh_api.criticality }}"
               only_on_ip="{{ undercloud_floating_ip | default(floating_ip) }}"
  notify: restart sensu-client
