---
dependencies:
  - role: openstack-meta
  - role: endpoints
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
  - role: logging-config
    when: logging.enabled|default(True)|bool
    service: cinder
    logdata: "{{ cinder.logs }}"
  - role: inspec
    install_inspec_controls: [cinder]
    tags: inspec
    when:
      - inspec.enabled|bool
      - inspec.controls.cinder.enabled|bool
  - role: openstack-source
    project_name: cinder
    project_rev: "{{ cinder.source.rev }}"
    rootwrap: True
    alternatives: "{{ cinder.alternatives }}"
    system_dependencies: "{{ cinder.source.system_dependencies }}"
    python_dependencies: "{{ cinder.source.python_dependencies }}"
    upper_constraints: "{{ cinder.source.upper_constraints }}"
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: cinder
    rootwrap: True
    alternatives: "{{ cinder.alternatives }}"
    when: openstack_install_method == 'package'
  - role: ceph-defaults
    when: ceph.enabled
  - role: openstack-distro
    project_name: cinder
    project_packages: "{{ cinder.distro.project_packages }}"
    rootwrap: True
    when: openstack_install_method == 'distro'
  - role: v7k-defaults

