---
- name: set up log rotation for keystone
  logrotate: name=keystone path=/var/log/keystone/*.log
  args:
    options:
      - daily
      - rotate 7
      - missingok
      - compress
      - minsize 100k
      - copytruncate
  when: openstack_install_method != 'distro'
 
