---
- name: create host aggs
  environment: 
    PYTHONPATH: "{{ basevenv_lib_dir|default(omit) }}"
  os_nova_host_agg:
    name: "{{ hostvars[item]['compute_ag'] }}"
    az: "{{ hostvars[item]['compute_ag'] }}"
    state: present
    validate_certs: "{{ validate_certs|default(omit) }}"
    auth:
      auth_url: "{{ endpoints.auth_uri }}"
      project_name: admin
      username: admin
      password: "{{ secrets.admin_password }}"
  run_once: True
  when: hostvars[item]['compute_ag'] is defined
  with_items: "{{ groups['compute'] }}"

- name: assign hosts to aggs
  environment:
    PYTHONPATH: "{{ basevenv_lib_dir|default(omit) }}"
  os_nova_host_agg_host:
    name: "{{ hostvars[item]['compute_ag'] }}"
    host: "{{ hostvars[item]['ansible_nodename'] }}"
    validate_certs: "{{ validate_certs|default(omit) }}"
    state: present
    auth:
      auth_url: "{{ endpoints.auth_uri }}"
      project_name: admin
      username: admin
      password: "{{ secrets.admin_password }}"
  run_once: True
  when: hostvars[item]['compute_ag'] is defined
  with_items: "{{ groups['compute'] }}"
