---
dependencies:
  - role: openstack-meta
  - role: endpoints
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
  - role: logging-config
    when: logging.enabled|default(True)|bool
    service: heat
    logdata: "{{ heat.logs }}"
  - role: inspec
    install_inspec_controls: [heat]
    tags: inspec
    when:
      - inspec.enabled|bool
      - inspec.controls.heat.enabled|bool
  - role: openstack-source
    project_name: heat
    project_rev: "{{ heat.source.rev }}"
    alternatives: "{{ heat.alternatives }}"
    system_dependencies: "{{ heat.source.system_dependencies }}"
    python_dependencies: "{{ heat.source.python_dependencies }}"
    python_post_dependencies: "{{ heat.source.python_post_dependencies }}"
    upper_constraints: "{{ heat.source.upper_constraints }}"
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: heat
    alternatives: "{{ heat.alternatives }}"
    when: openstack_install_method == 'package'
  - role: openstack-distro
    project_name: heat
    project_packages: "{{ heat.distro.project_packages }}"
    python_post_dependencies: "{{ heat.distro.python_post_dependencies }}"
    when: openstack_install_method == 'distro'
  - role: openstack-database
    database_name: heat
  - role: openstack-firewall
    rule_name: heat
    rules_type_input:
      - { protocol: tcp, port: "{{ endpoints.heat.port.haproxy_api }}" }
      - { protocol: tcp, port: "{{ endpoints.heat_cfn.port.backend_api }}" }
