---
- name: check nova services
  command: /etc/sensu/plugins/check-nova-services.sh
  register: result
  until: result | succeeded
  retries: 5
  delay: 10
  delegate_to: "{{ groups['controller']|first }}"

- name: check neutron agents
  command: /etc/sensu/plugins/check-neutron-agents.sh
  register: result
  until: result | succeeded
  retries: 5
  delay: 10

- name: cluster health check on db_arbiter
  command: /etc/sensu/plugins/percona-cluster-size.rb -d /root/.my.cnf --expected 3 --criticality critical
  register: cstat
  until: cstat | succeeded
  retries: 5
  delay: 10
  delegate_to: "{{ groups['controller']|first }}"
  when: inventory_hostname in groups['db_arbiter']
