---
- hosts: network
  tasks:
  - include: ../roles/neutron-data-network/tasks/igmp-router.yml
  handlers:
  - include: ../roles/neutron-data-network/handlers/main.yml

- hosts: network:compute
  tasks:
  - name: Add BlueBox OpenStack PPA
    apt_repository: repo='ppa:blueboxgroup/openstack'
    register: result
    until: result|succeeded
    retries: 5

  - name: Upgrade iproute to support VXLAN
    apt: name=iproute=1:3.12.0-2~ubuntu12.04.1~ppa1
    register: result
    until: result|succeeded
    retries: 5

  - name: Upgrade kernel to support VXLAN
    apt: pkg=linux-generic-lts-raring
    notify: tag for restart
    register: result
    until: result|succeeded
    retries: 5

  handlers:
  - name: tag for restart
    set_fact: do_reboot=True
