---
stack_env: example_allinone
floating_ip: 172.16.0.100

xtradb:
  sst_auth_password: asdf

percona:
  replication: False

primary_interface: 'ansible_eth1'
provider_interface: 'ansible_eth2'


ironic:
  enabled: True
  logging:
    debug: False
  flavors:
    - name: 'baremetal'
      ram: 512
      disk: 19
      vcpus: 1

cinder:
  enabled: False

heat:
  enabled: False
  logging:
    debug: False

neutron:
  enable_external_interface: True
  networks:
    - name: provider
      shared: true
      router_external: true
      provider_network_type: flat
      provider_physical_network: provider
      tenant_name: admin
      external: true
      segmentation_id: null
    - name: private
      tenant_name: demo

nova:
  compute_driver: ironic.IronicDriver
  reserved_host_disk_mb: 0
  controller_reserve_ram: 0
  compute_reserve_ram: 0
  enable_novnc: False
  compute_ag: baremetal
  zone: AZ1

sensu_checks:
    percona:
      check_cluster_size:
        sudo: true
        handler: default
        notification: "unexpected number of mysql processes"
        interval: 120
        standalone: true
        command: "percona-cluster-size.rb -d /root/.my.cnf --expected 3 --criticality critical"
        service_owner: openstack
        dependencies: "{{ 'keepalive' | sensu_dependencies(hostvars, groups, 'db') }}"
        # above is incredibly ugly, but works. Creates the list below.
        #dependencies:
        #  - "controller1.ursula-vagrant/keepalive"
        #  - "controller2.ursula-vagrant/keepalive"
        #  - "compute1.ursula-vagrant/keepalive"
      check_mysql_process:
        handler: default
        notification: "unexpected number of mysql processes"
        interval: 120
        standalone: true
        command: "check-procs.rb -p mysql -W 1 -C 1"
        service_owner: openstack
      check_garbd_process:
        handler: default
        notification: "unexpected number of garbd processes"
        interval: 120
        standalone: true
        command: "check-procs.rb -p garbd -W 1 -C 1"
        service_owner: openstack
