---
- name: set up log rotation for nova
  logrotate: name=nova path=/var/log/nova/*.log
  args:
    options:
      - daily
      - missingok
      - rotate 7
      - compress
      - notifempty
      - delaycompress
  when: openstack_install_method != 'distro'

