---
- name: add mongodb arbiter to replica set
  mongodb_replication:
    login_host: "{{ mongodb.endpoint_addr }}"
    login_port: "{{ mongodb.port }}"
    login_user: "admin"
    login_password: "{{ mongodb.db_password }}"
    replica_set: "{{ mongodb.replica_name }}"
    host_name: "{{ primary_ip }}"
    host_port: "{{ mongodb.port }}"
    host_type: "arbiter"
  when: inventory_hostname in groups['mongo_arbiter']
  no_log: true
